### ISSUE TITLE
RC10 issues

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#102]
Here's a video because this is hard to explain/visualize https://dl.dropboxusercontent.com/u/105549/RC10.mp4

Basically I took no action on the notifications and instead tried to see if they would be displayed for 3 sessions followed by a 24 hr interval. This didn't work and the results were inconsistent. 

 - After the first 3 sessions, the 2nd notification showed instead of the expected 24 hr interval
 - The 2nd notification was shown for 4 sessions and then there was a 24 hr interval
 - The 3rd notification was shown for 2 sessions and then the 4th notification was shown without a 24 hr interval before it
- The 4th notification was shown 3 times followed by a 24 hr interval
- The 5th notification was shown 1 time and then the 6th notification was shown without a 24 hr interval before it.
 - The 6th notification was shown 4 times followed by a 24 hr interval

Next, I wanted to see if the queue of not-acted-upon notifications would display correctly. I took action on each one of these. This seemed to work as expected except for the 6th notification which was never displayed a second time.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mozilla/onboard/pull/104
