### ISSUE TITLE
Please don't send data to Google Analytics

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/onboard#122]
GA is a privacy-hostile service and Firefox wants to be a privacy-friendly browser. This is the reason why some of us use Firefox and it is a big part of Mozilla's marketing campaign.

I know Google Analytics is practical or hip or whatever but please use some self hosted solution and not [send data to Google](https://github.com/mozilla/onboard/commit/db4d6c8726c89a5d6a241c1b1065827b525c5baf).

Thank you!

**Comment by grauenwolfe** [comment]
No Googly Anal, Firefox. C'mon, you know better.

**Comment by mikhoul** [comment]
Why this happen ?  I trusted Firefox over Chrome to be honest but no longer... 

There is no mention of this anywhere not even on AMO: http://i.imgur.com/Vp3m4z0.png  😠

**Comment by callahad** [comment]
> *As an aside, I'd like to reiterate that Mozilla [explicitly negotiated with Google](https://bugzilla.mozilla.org/show_bug.cgi?id=697436#c14) to ensure that any data we store in Analytics cannot be mined, tracked, or reused (even internally) by Google. The product we're paying for is not the same as the free, off-the-shelf Google Analytics, and cannot be used to track you across the Web.*

For context, there's currently [a misleading post on Reddit](https://www.reddit.com/r/firefox/comments/6n4r9b/firefox_send_data_to_google_analytic_on_every/) falsely claiming that "Firefox send data to Google Analytic on every browser startup and did not disclose it again," where the "again" is referencing [a bug with remote content in `about:addons`](https://github.com/mozilla/addons/issues/3145) that was [fixed within 24 hours](https://github.com/mozilla/addons/issues/3145).

This experimental onboarding add-on does not appear to be actively developed nor generally distributed, therefore I believe this is currently a non-issue. @schalkneethling, can you please confirm?

I'm also locking the conversation to keep the signal/noise ratio in check. Non-technical discussion and advocacy can happen in [the Reddit thread](https://www.reddit.com/r/firefox/comments/6n4r9b/firefox_send_data_to_google_analytic_on_every/).

**Comment by schalkneethling** [comment]
@callahad Indeed, as far as I know, this is no longer distributed. There are however other initiatives with regards to onboarding that may still be doing some of the things this add-on did in terms of GA.

I no longer work on this nor the other project so, best person to speak I believe might be @Verdi

**Comment by callahad** [comment]
Thanks for the followup. I did some digging and it looks like this was used as part of a Funnelcake experiment. Funnelcake is our A/B testing tool for custom features in new installations of Firefox. We've been doing Funnelcake builds for a [nearly a decade](https://blog.mozilla.org/metrics/2007/10/30/we-shipped-funnelcake01/).

This specific experiment added tips to the bottom of the new tab page which introduced users to Firefox Sync, Add-ons, etc. and measured whether or not those tips were effective at getting users to try out those features and stick with Firefox.

The experiment was enabled for two weeks at the start of May, and only for (at most) 4% of new, 32-bit, `en-US` installations of Firefox on Windows. It also effectively [self-destructed](https://github.com/mozilla/onboard/blob/2a9dedaea6feb51c0d0a5a465a45ad85e98356fc/index.js#L41-L46) once all six tips [had been displayed](https://github.com/mozilla/onboard/blob/2a9dedaea6feb51c0d0a5a465a45ad85e98356fc/lib/flow-manager.js#L123-L135).
