### ISSUE TITLE
Implement notification design spec

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#46]
More in https://drive.google.com/open?id=0B2y0OSD97CR6QnpHVG1lODRrQ3M
![notification spec](https://cloud.githubusercontent.com/assets/107992/24630650/16df8cc6-1883-11e7-8ff0-c1c1a3e62dbe.png)

**Comment by schalkneethling** [comment]
Some of the font sizes mentioned are way to small and pose an accessibility issue. The light gray on white is to low contrast and again poses a11y issues.

With regards to the button on the right. This is clearly designed for people with large viewports and, looking at the general audience, it would make more sense to have the button below the copy from the start.

Thoughts?

**Comment by Verdi** [comment]
- The light gray text is meant to be incidental but it couldn't hurt to increase the contrast. I'll update that. 
- The 12px font size is what we use for snippets and things like tab labels, menu item labels, etc.
- The spec is for a 1366 wide screen which is the most common (more than 80% have a screen at least this wide). But the design can be responsive down to about 900px by dropping the "Welcome to Firefox" text, making the outside margins smaller and bringing the progress and close buttons closer to the content. For a browser window smaller than 900px we can just crop the snippet (or maybe make it scroll horizontally). Below this point many websites and apps scroll so the user is probably trying to do something else besides reading and acting on the notification.
  - 1024 wide screen
![1024notification](https://cloud.githubusercontent.com/assets/107992/24662779/bb399314-191b-11e7-8123-6028b6d68ec3.png)
  - Smaller browser window
![smallnotification](https://cloud.githubusercontent.com/assets/107992/24662839/ee5d8912-191b-11e7-9efe-aaa3cc3159c3.png)

**Comment by Verdi** [comment]
"Progress Pill" and Welcome to Firefox
 - The background color on the pill is the same as the "Welcome to Firefox" text - #767676
 - It's border radius is 12px.
 - The whole notification is 120px tall and the pill & text is centered vertically.
 - When the space between the end of "Welcome to Firefox" and the notification icon to the right is less than 50px, drop "Welcome to Firefox"
![screen shot 2017-04-07 at 5 06 32 pm](https://cloud.githubusercontent.com/assets/107992/24821514/a6cdd976-1bb4-11e7-98dd-9f7c54daebc5.png)

**Comment by Verdi** [comment]
Notification Content:
- The icon is 64X64 max with 15px between it and the text to  the right.
- The text box should be 420px wide with 15px between it and the button to the right.
- The button text should be on one line and have 15px of padding left and right. The button itself is 40px tall.
- This whole section should be centered vertically and horizontally.
![screen shot 2017-04-07 at 5 41 20 pm](https://cloud.githubusercontent.com/assets/107992/24822271/7579a6de-1bb9-11e7-8842-51dc8ffa8e8c.png)

**Comment by Verdi** [comment]
Close button:
- Only visible when the pointer is over the notification
![screen shot 2017-04-07 at 5 46 53 pm](https://cloud.githubusercontent.com/assets/107992/24822391/6bd9a556-1bba-11e7-84f9-1fec7bdb3453.png)

 - The close button has it's own hover state:
![screen shot 2017-04-07 at 5 48 11 pm](https://cloud.githubusercontent.com/assets/107992/24822437/d8c76c0c-1bba-11e7-8bb1-ed8dc95a520a.png)

**Comment by schalkneethling** [comment]
Posted by @jenniferdavidson

## Design Request: Raccoon face for private browsing

@mart3ll @verdi
Is it too late to ask for a new asset? I'm thinking it would be neat to include the private browsing raccoon face, instead of the emoji style face on the private browsing notification. What do you both think?

@schalkneethling

As we still need to get the GA things done and incorporated, we have some time but, it will depend on Sean's availability. Easy for me to update.

**Comment by schalkneethling** [comment]
Posted by @jenniferdavidson

## Design request: Add a Firefox logo or fox icon

This one is for Michael. @verdi
Can we add some fox icon or Firefox logo on the notification design? I'm just noticing that the only branding we have is the words 'Welcome to Firefox', and I'm wondering if we'll see the same issues as Onboarding v1.1 where the branding wasn't clear enough and participants weren't sure that it was actually Firefox serving up these notifications.

**Comment by Verdi** [comment]
RC6: The height of the notification bar is 163px - should be 120px.

**Comment by Verdi** [comment]
RC6: The "pill" and "Welcome to Firefox" is 245px from the left edge - should be 50px.

**Comment by Verdi** [comment]
RC6: Drop "Welcome to Firefox" when it's closer than 50px to the notification icon to the right.

**Comment by Verdi** [comment]
RC6: Everything in the notification should be centered vertically but it's not.

**Comment by Verdi** [comment]
RC6: Icon, notification copy and button should be centered horizontally as a group but they're not.

**Comment by Verdi** [comment]
RC6: Button is 48px high - should be 40px.

**Comment by Verdi** [comment]
RC6: Button text should be Segoe UI Bold, 12px.

**Comment by Verdi** [comment]
RC6: Button color should be #0094FB, border color should be #006ECF, and the radius should be 2px.

**Comment by Verdi** [comment]
RC6: Please make the headline font smaller and reduce the bottom margin.

**Comment by Verdi** [comment]
RC6: Close button should be 56px from the right; 50px for the hover version.

**Comment by schalkneethling** [comment]
All other copy is `sans-serif` and the standard across Mozilla(for now) is Open Sans so, wonder we should just use Open Sans instead of Segoe UI Bold? With that said, including a font for just one piece of copy is going to increase the size of the add-on, and I am not sure if the payoff is large enough. Thoughts?

**Comment by Verdi** [comment]
So this is not supposed to be a web property, it's part of the product so I wanted to use system default fonts. Would we have to include Segoe UI? Wouldn't it be on the user's computer? We can use open sans as a fallback for the odd case where it fails for some reason. @pdolanjski are we going to have Windows XP in this test (they have a different default font)?

**Comment by schalkneethling** [comment]
> Would we have to include Segoe UI? Wouldn't it be on the user's computer?

If we feel confident enough that it would be on the users computer then no, I can just specify that, with a fallback to sans-serif

**Comment by pdolanjski** [comment]
No Windows XP.  XP users are now on the ESR 52 release and won't get future
versions.

On Tue, Apr 11, 2017 at 11:23 AM, Schalk Neethling <notifications@github.com

**Comment by schalkneethling** [comment]
Font change landed in https://github.com/mozilla/onboard/pull/88

**Comment by Verdi** [comment]
Here's a few last tweaks:
![rc8-tweaks](https://cloud.githubusercontent.com/assets/107992/25010310/618d3080-202f-11e7-9cdb-ee4b31dcb0e3.png)

**Comment by schalkneethling** [comment]
@Verdi How does this look?

![screen shot 2017-04-13 at 18 40 11](https://cloud.githubusercontent.com/assets/10350960/25014674/01898cc0-2079-11e7-9ec2-8620ec3aaf1b.png)

And on hover

![screen shot 2017-04-13 at 18 41 34](https://cloud.githubusercontent.com/assets/10350960/25014683/0845c4b6-2079-11e7-87a0-0589d1644d79.png)

**Comment by schalkneethling** [comment]
Missed the bold of the copy on the button. I have added that locally.

**Comment by schalkneethling** [comment]
Also, should we bump the font size and letter spacing a little now that it is bold?

Before

![screen shot 2017-04-13 at 18 46 40](https://cloud.githubusercontent.com/assets/10350960/25014825/a45c6332-2079-11e7-8e00-6a47b9988e50.png)

After

![screen shot 2017-04-13 at 18 46 50](https://cloud.githubusercontent.com/assets/10350960/25014828/a972c410-2079-11e7-8edc-05674b173c02.png)

**Comment by Verdi** [comment]
Almost there
![rc8-tweaks2](https://cloud.githubusercontent.com/assets/107992/25015561/f3afd5d2-2041-11e7-9510-e64472f652e5.png)

**Comment by schalkneethling** [comment]
@Verdi Here are a couple of screen shots. To make it as responsive as possible, I had to make a few calls here and there with regards to width, positioning etc. Let me know your thoughts.

![screen shot 2017-04-13 at 21 12 30](https://cloud.githubusercontent.com/assets/10350960/25020339/36828a84-208e-11e7-95ff-1bb8eaccdf70.png)

![screen shot 2017-04-13 at 21 12 46](https://cloud.githubusercontent.com/assets/10350960/25020345/3c17d10c-208e-11e7-8b42-fea656783bd0.png)

    
![screen shot 2017-04-13 at 21 13 04](https://cloud.githubusercontent.com/assets/10350960/25020357/45a5c508-208e-11e7-9e1f-e338998e2748.png)

![screen shot 2017-04-13 at 21 13 27](https://cloud.githubusercontent.com/assets/10350960/25020368/4c4b9c2a-208e-11e7-91d2-04b91fabee58.png)

**Comment by Verdi** [comment]
Mainly the button needs to go in the same group as the icon and text and then that group gets centered. 
![rc9](https://cloud.githubusercontent.com/assets/107992/25028854/330c28da-207d-11e7-9df2-4b1aa6782cf0.png)

**Comment by schalkneethling** [comment]
Gotcha, seems like you want the whole thing generally more left aligned(except for the x out button) rather then taking about the entire available space. I will make this update an cut a new release.

Thank you for your continued testing and feedback.

**Comment by Verdi** [comment]
Hi Schalk - I was looking at the notification markup and css with another mozillian and we thought it might be easier to get the right alignment (progress on left, icon+text+button centered, close on the right) and make it responsive by using grid. Here's a codepen example - https://codepen.io/jensimmons/pen/RVNBdo - this seems to work pretty well.

**Comment by schalkneethling** [comment]
Thanks @Verdi it looks great, will update.
