### ISSUE TITLE
There should be 24 hours between notifications

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#47]
When I tested the xpi today, I clicked on one notification CTA and then received the next notification when I opened the next new tab. We should wait 24 hours. The user will be able to go though all the tours one after the other when we implement the overlay. Even then, the notifications should be 24 hours apart.
From the tour requirements doc:
Display the next notification on the first session or first new tab that is opened at least 24 hours after the previous notification was stopped being displayed.

**Comment by schalkneethling** [comment]
Hey @Verdi - My mistake for not adding a note to the testing doc but, to make testing a little less tedious, the timer is set to 4 seconds. I was thinking to up this to 10 but, when released, it will be 24 hours.
