### ISSUE TITLE
Close button should only be shown when hovering over notification

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#48]
We don't want the close button to be visible all the time.

When the notification bar is hovered over or tapped, show the close button. When the close button is hovered over or long-pressed, show the highlight state and the tool tip, "Don't show this message anymore"

![closebutton](https://cloud.githubusercontent.com/assets/107992/24668210/b56f6e76-192b-11e7-9645-feff8f870437.png)
![closebutton 2x](https://cloud.githubusercontent.com/assets/107992/24668212/b57cb5e0-192b-11e7-83a0-f13f667b0680.png)
![closebuttonh](https://cloud.githubusercontent.com/assets/107992/24668213/b57e54fe-192b-11e7-979c-68fed1da4bd9.png)
![closebuttonh 2x](https://cloud.githubusercontent.com/assets/107992/24668211/b578eb18-192b-11e7-9670-7b4afe9ec03e.png)

**Comment by schalkneethling** [comment]
Do we have SVG versions of these icons? I will implement with the PNG files but, would be nice to have as SVG. Thanks!

**Comment by schalkneethling** [comment]
I created two SVG icons for the based on the provided PNG files. Have a look at them when testing the latest XPI. If they will not work, please ask Sean to provide me with the SVG files. Thanks!

**Comment by Verdi** [comment]
[closebuttons.zip](https://github.com/mozilla/onboard/files/896448/closebuttons.zip)
