### ISSUE TITLE
Missing a selected/visited state for notification button

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#49]
Tab 1: New tab w/tiles & "Reduce clutter" notification
Tab 2: Create a Firefox accounts

On Tab 1, I clicked on the "Sign up for sync" button on step 1 of the Onboarding Tour. It opens a new tab and directs to setting up a Firefox account (Tab 2). After I set up a Firefox account, I went back to Tab 1. The notification is still present, and there is no indication that I clicked the button "Sign up for sync" already. 

A potential change (that should be reviewed by verdi/Michelle): When a button has been selected, change the color of the button to indicate that it has been clicked, add a 'checkmark', and/or some text into the button after it has been clicked.

**Comment by Verdi** [comment]
I wrote the spec to say that we should dismiss the notification when clicked. In the future, with the overlay, clicking the notification will dismiss it and open that section of the overlay.

**Comment by jenniferdavidson** [comment]
Ah! So the notification should just disappear when the button is clicked. Does that need to be filed as an issue, then?

**Comment by Verdi** [comment]
Filed https://github.com/mozilla/onboard/issues/53

**Comment by jenniferdavidson** [comment]
Sounds good. Closing this.
