### ISSUE TITLE
Update tiles on new tab page?

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#50]
The tiles shown are the 'old' 'Get Firefox for Android', 'Firefox Sync', etc. tiles on the new tab page. Are those going to be updated to be either "Top Sites" or something else? We have received negative feedback in past research about the existing tiles.

**Comment by Verdi** [comment]
Yes, it's a pref that will get set when we make the funnelcake. It will look just like the ones in the 2.0 funnelcake.

**Comment by jenniferdavidson** [comment]
Sounds good!
