### ISSUE TITLE
"Do you want to change your default web browser" dialog box appears in the background

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#51]
I clicked on Notification 6 of 6 to make Firefox my default browser, and the dialog box to ask me if I wanted to change my default web browser appeared behind my browser window.

**Comment by Verdi** [comment]
This did not happen for me on Windows 10. Jennifer, what OS did you test on?

**Comment by jenniferdavidson** [comment]
I tested on MacOS, as Schalk's instructions for setting up the add-on talked about the "Terminal App" and seemed to be MacOS-based instructions.

**Comment by schalkneethling** [comment]
I also get random experiences where it is in the background and sometimes in the foreground on Mac but, as we are aiming at Windows users with the experiment and it works there, I am going to close this issue for now. Thanks for reporting @jenniferdavidson
