### ISSUE TITLE
Point to where to change the default browser instead of a dialog box?

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#52]
This is not a bug. It's a feature request/requirements change request. 

I'm wondering if the button the last notification can somehow point to the preferences area where a user can change their default browser instead of making a dialog box appear? If we make a dialog box appear, the user does not know where to find how to change their default browser if they want to do it in the future.

**Comment by Verdi** [comment]
I think this can be handled by copy in the overlay section for this item. We also want to talk to the user about pinning Firefox to their taskbar/dock which may be even more important than default status.

**Comment by jenniferdavidson** [comment]
So do you think we should just leave this as-is for this funnelcake, @verdi?

**Comment by Verdi** [comment]
We should leave it as is for this funnelcake.

**Comment by jenniferdavidson** [comment]
Deal. Closing.
