### ISSUE TITLE
Notification should be dismissed once user clicks the CTA

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#53]
From the requirements doc:
Close the notification and don’t display it again if the user takes action on (either clicks on the CTA or dismisses) the notification.

**Comment by schalkneethling** [comment]
This has been resolved in https://github.com/mozilla/onboard/pull/56

**Comment by Verdi** [comment]
When I tested v1.0.0-beta2 (I only got the sync notification), clicking the Sync CTA did not close the notification.
