### ISSUE TITLE
Send Get an Add-on to "Get Add-ons" instead of Extensions

### ISSUE THREAD

**Issue by pdolanjski** [mozilla/onboard#55]
Currently, clicking the Get an Add-on and the subsequently highlighted button brings you to the Extensions category on about:addons.  It's not evident how to find add-ons from there.  The Get Add-ons section would be much better.  

(not sure if there is a technical reason why we can't do this)

**Comment by schalkneethling** [comment]
@pdolanjski We do not have any control over where the icon in the menu links to from the add-on but, perhaps there is a preference that can be flipped for the funnelcakes to have that icon send users to `Get Add-ons`?

It seems that `about:addons` default to showing you your installed add-ons.

**Comment by Verdi** [comment]
At least a new profile should default to the Get Add-ons section.

**Comment by schalkneethling** [comment]
@Verdi I do not believe so. The way I test the add-on( with `jpm`) it creates a new tmp profile every time I launch the project(unless I pass a flag to reuse the same). It might be that the default profile for dev edition is different to release though so perhaps.

Is there someone we can ask to confirm?

**Comment by Verdi** [comment]
On new profiles (as long as you have not been to the add-ons manager before), clicking the Add-ons button in the menu takes you to the Get Add-ons pane in all versions of Firefox.

**Comment by schalkneethling** [comment]
Thanks for clearing that up @Verdi
