### ISSUE TITLE
v1.0.0-beta2 only opens the first notification

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#60]
I've tried twice with Dev Edition on Windows 10 and I only get the first (sync) notification. Closing Firefox, setting my system clock forward and relaunching Firefox does not bring up the next notification.

**Comment by schalkneethling** [comment]
I believe we cleared this up over Slack?

**Comment by Verdi** [comment]
Not sure what is going on. This time I got more notification but only 1, 3, 5 and 6. And 6 showed up twice? I uploaded a video in Slack.
