### ISSUE TITLE
Notification 5 did not show up

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#66]
OS: MacOS
Onboarding Version: beta3

Using the "Default Flow" wiki instructions, I did not see Notification 5. It went from 4 to 6.

@schalkneethling

**Comment by jenniferdavidson** [comment]
The second time I tested this, I saw Notification 5. Let's have 1 more person confirm that they see it, and we can close this.

**Comment by schalkneethling** [comment]
Thanks @jenniferdavidson - Let's see if someone else runs into this as well. I would say, if you run into a possible bug like this(i.e. on that needs a second pair of eyes), ping folks on Slack and point them to this issue. Thanks again.

**Comment by schalkneethling** [comment]
No additional confirmation so closing for now. Feel free to reopen should this be confirmed.
