### ISSUE TITLE
The testing timing was wonky - had to close and open a new tab twice to trigger

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#67]
OS: MacOS
Onboarding Version: beta3

For the first and 4th notification, I had to close and open a new tab multiple times (I believe twice) before the notification showed up. 

(This may be an artifact of the test timing, but I thought it was worth noting.)

@schalkneethling

**Comment by schalkneethling** [comment]
@jenniferdavidson Are you using the XPI from here https://github.com/mozilla/onboard/releases/tag/v1.0.0-beta3 or the one I uploaded to Slack?

Nothing different code wise but, the one on Github has a 30 sec timer and the latter has a 10sec timer so, things happen/change more quickly.

**Comment by schalkneethling** [comment]
I also know that there is an issue with about:newtab where Fx caches it aggressively and so, sometimes one needs to open the newtab twice for it to kick in.
