### ISSUE TITLE
(may be a feature) Notification does not appear if 'Choose What I Share' notification is up

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#68]
OS: MacOS
Onboarding Version: beta3

This may be the intended design, but when the 'Choose What I Share' notification is on the bottom of the window, the Onboarding notification does not appear. I had to close the 'Choose What I Share' notification to see the first Onboarding notification. 

How will this work in the wild? How will this impact user research? If the user never addresses the 'Choose What I Share' notification, what happens?

**Comment by schalkneethling** [comment]
Interesting, I have not experienced this. Will test and see. It should not impact the add-on so not, not a feature :-/

**Comment by Verdi** [comment]
Yeah we won't be showing that "choose what I share" notification in our test. We'll be opening the privacy notice in a second tab instead.
