### ISSUE TITLE
Design request: Add a Firefox logo or fox icon

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#69]
This one is for Michael. @verdi 

Can we add some fox icon or Firefox logo on the notification design? I'm just noticing that the only branding we have is the words 'Welcome to Firefox', and I'm wondering if we'll see the same issues as Onboarding v1.1 where the branding wasn't clear enough and participants weren't sure that it was actually Firefox serving up these notifications.

**Comment by schalkneethling** [comment]
Moved to https://github.com/mozilla/onboard/issues/46
