### ISSUE TITLE
Design Request: Raccoon face for private browsing

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#71]
@mart3ll @verdi

Is it too late to ask for a new asset? I'm thinking it would be neat to include the private browsing raccoon face, instead of the emoji style face on the private browsing notification. What do you both think?

**Comment by schalkneethling** [comment]
As we still need to get the GA things done and incorporated, we have some time but, it will depend on Sean's availability. Easy for me to update.

**Comment by schalkneethling** [comment]
Tracked here: https://github.com/mozilla/onboard/issues/46#issuecomment-292995481
