### ISSUE TITLE
rc6 - 2nd notification not displayed, 1st repeated even with user action

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#82]
I just tested RC6 on Windows 10. I saw notifications: 1, 3, 4, 5, and 6. I dismissed each one of them. I waiting 60 more seconds to see if maybe #2 had been added to the queue to display later and instead of seeing that I saw #1 even though I'd explicitly dismissed it the first time around.

**Comment by jenniferdavidson** [comment]
Ditto with not seeing Notification 2.

Verison: Onboarding rc8
Operating System: Windows 7 in a VM

I saw the first notification (in my case it was 'sync'), then I clicked "Sign up for Sync". I closed the Create an Account tab as well as the tab that had the Sync notification on it. Then I opened a new tab. I saw notification 3, and did not see notification 2.

**Comment by schalkneethling** [comment]
Anyone still experiencing this?
