### ISSUE TITLE
Queue of not acted upon notifications doesn't work correctly.

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#84]
With RC6 on Windows 10:
I got each notification, did not act, waited 60 seconds and got the next notification. After I'd seen all six, I expected to see all six one more time but instead I saw the last notification a second time and then did not see any more notifications.
https://www.dropbox.com/s/8zf0xr2uhj19yhg/rc6-noaction.mp4?dl=0

**Comment by schalkneethling** [comment]
Will be resolved by latest RC released later today
