### ISSUE TITLE
No Interaction Flow: If a new tab is opened before time, there is no notification shown

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#90]
Not sure if this is an actual issue or how it's designed. 

Step 1. Open a new tab (Tab 1). See a notification.
Step 2. Wait less than a minute. Open a new tab (Tab 2).
Outcome: On the new tab, NO notification appears. 

Question: Should the notification from Tab 1 appear on Tab 2, since it's 'been less than 24 hours'? Or do we only show the notification on 1 new tab for 24 hours? 

@schalkneethling @verdi

**Comment by Verdi** [comment]
We should be showing them on all new tabs until you click the CTA, dismiss it or reach 3 sessions or 24hrs.

**Comment by schalkneethling** [comment]
@jenniferdavidson You say:

> Step 2. Wait less than a minute. Open a new tab (Tab 2).

You say you waited less than a minute. The current timers are set at 30 seconds each so, the notification will be shown for 30 seconds(24 hours during release), and then enter an interval of 30 seconds(24 hours during release) for which no notification will be shown. After that, the flow will move on to the next notification.

So, if you waited less than a minute but, more than 30 seconds, then what you saw is 100% correct.

**Comment by jenniferdavidson** [comment]
That seems to contradict what @verdi said "We should be showing them on all new tabs until you click the CTA". I waited less than a minute but more than 30 seconds, but from what Verdi said the notification (from Tab 1) should appear on the new tab (Tab 2) before the next notification appears, regardless of the length of time it has been.

**Comment by schalkneethling** [comment]
@jenniferdavidson 

> "We should be showing them on all new tabs until you click the CTA"

then he also states

> "or reach 3 sessions or 24hrs."

24hrs here equal 30 seconds. The way it works is 

## No interaction

* For 30(24h) seconds the notification is shown
* For 30(24h) seconds no notification is shown

The tour moves onto the next notification

## Interacted

* For 30(24h) seconds the notification is shown unless,
1. The user clicks the CTA or,
2. Dismiss the notification

* If one of the above actions happen, the tour immediately goes into 30(24h) seconds while no notification is shown

At which point, the tour moves onto the next notification

**Comment by jenniferdavidson** [comment]
Ahhh - ok! Thanks for the clarification. I'll close this issue then.
