### ISSUE TITLE
rc8: CTA Button text is not bold

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#91]
The call to action text on the button should be bold. It should look like this: https://cloud.githubusercontent.com/assets/107992/24822271/7579a6de-1bb9-11e7-8842-51dc8ffa8e8c.png

See screenshot for how it looks on Windows 7 in a VM. The text on the button is not bold.
![screen shot 2017-04-11 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/911251/24932440/6dba4f38-1ec6-11e7-98bb-923faf85de0b.png)

**Comment by jenniferdavidson** [comment]
Here's a previous comment about the same issue: https://github.com/mozilla/onboard/issues/46#issuecomment-293093694

**Comment by schalkneethling** [comment]
Fixed in https://github.com/mozilla/onboard/pull/95
