### ISSUE TITLE
When Firefox is my default browser, clicking on "Make Firefox Your Default Browser" shows UAC that leads to nothing.

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/onboard#92]
Version: Onboard-v1-rc8
OS: Windows 7 in a VM

Steps:
**Step 1.** Install Firefox Developer Edition. In Firefox Developer Edition, there's a checkmark that is pre-selected to make Firefox Developer Edition my default browser. Leave that checkmark checked.

**Screenshot of Installer where default browser checkbox is pre-selected**
![screen shot 2017-04-11 at 2 56 51 pm](https://cloud.githubusercontent.com/assets/911251/24933037/150b4ace-1ec9-11e7-8604-7084278c021c.png)

**Notification 6** 
![screen shot 2017-04-11 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/911251/24933017/fea66e94-1ec8-11e7-9e7e-56a2094b5eff.png)

**UAC**
![screen shot 2017-04-11 at 3 04 45 pm](https://cloud.githubusercontent.com/assets/911251/24933021/03528af4-1ec9-11e7-8c46-ba97ce8a616b.png)

**Step 2.** Go through the notifications until I get to Notification 6. Click on "Make Firefox Your Default Browser. UAC appears. 

**Step 3.** Click "Yes" on UAC. 

**Outcome:** The UAC dismisses, something seems to 'refresh' but nothing happened in the browser. There's no confirmation that anything was different.

**Suggested Outcome:** Either - 1) Grey out CTA and replace button text with "Firefox is already your default", or 2) When the CTA is clicked, show a window that notifies the user that thanks them for having Firefox as their default browser already. 

@verdi @schalkneethling

**Comment by Verdi** [comment]
So for our experiment we're going to use the installer without the pre-checked make Firefox your default browser (only works in Vista and 7). But the notification should be smart and not be shown if Firefox is your default (you could make this change outside of the notification). Firefox knows if it's the default browser. 

Clicking the CTA should dismiss the notification. It would be good to have a success message somewhere (where?) but I don't believe that's ever really done on Windows 7 (it just gets set silently) - let me think - booting up the VM...

**Comment by jenniferdavidson** [comment]
If the notification is not shown when the browser is already their default, then the Y "X of Y" on the pill style numbering would need to be variable. If Y is hard coded, we'd need to change it to be variable based on the number of notifications. It seems like that might be a pain, because what if they see 3 notifications, then change it to be their default, then see 2 more. The "of X" part of the pill would change from "of 6" to "of 5". People probably wouldn't notice it, but it seems odd.

**Comment by schalkneethling** [comment]
This was not part of the initial spec but, I am going to look at some code that is used on mozorg and see whether that can be reused inside the add-on to detect whether Firefox is the user's default browser. If it is, perhaps we can simply use the final notification to thank them for having Firefox set as their default.

Anything more at this point will mean additional development time, which introduces new variables to the flow, which means the possibility of bugs, which means additional testing time will be needed, which will most likely lead to additional delay getting the add-on out into the wild.

While making these changes might be worth the knock on effect mentioned above, we would need to confirm that Peter, Nicole, and perhaps RelEng is fine with it.

**Comment by jenniferdavidson** [comment]
@schalkneethling Did you include this in rc8 already? I I did not see Notification 6 when I was testing with Firefox Developer Edition as my default browser. Is that the behavior you're going for? If so, the pill still said "5 of 6" on notification 5, which needs to be fixed. Perhaps we should update the text on the pill to be "5 left" or "5 more" or something like that? I'm not sure if that's clear enough but it does remove the need to know the total number of notifications that are being shown.

**Comment by jenniferdavidson** [comment]
Well then. I was not able to replicate what I mentioned in the previous comment.

Here's what I tried, and I still got Notification 6:
Notification 1 - Dismiss
Notification 2 - Click CTA
Notification 3 - Click CTA
Close browser
Open browser
Notification 4 - X out
Make FF Developer Edition my Default Browser
Notification 5 - No interaction, close tab
Notification 6 - appeared! 

I think that's right because I don't think the code changed, but we should still figure out that case.

**Comment by schalkneethling** [comment]
@jenniferdavidson Indeed, I have not built that in yet because the discussions still needed to be concluded. It seems that the UITour can at least initially tell us whether Firefox is set as default at the start of the tour but, from my initial testing it seems this is not actually possible from the add-on(I get a undefined error)

I am going to look into it a little more. Sometimes the way UITour is used on a webpage and the way it is used from the add-on is slightly different so, it might still be possible.

I do not know when the configuration is updated so, I am not sure if we will be able to detect whether the user actually set Firefox to their default at step 6 but, will have a look at the possibilities here as well. 

In the mean time, it would be could if the team can decide whether or not this is something we want to add now, or whether we want to keep it as is.

Thanks for testing!

**Comment by schalkneethling** [comment]
Discussed with Verdi and Peter in today's standup, for this iteration of the experiment, we are going to leave this interaction as is. Closing.
