### ISSUE TITLE
Should we keep the newtab panel up when elements in chrome open?

### ISSUE THREAD

**Issue by sevaan** [mozilla/onboard#93]
When I click on a button like “One Click Search”, it opens the search panel but immediately closes the panel at the bottom of newtab.

Doing this, I immediately lose my context, and maybe I was still reading the string as I clicked the button. Maybe it’s worth keeping it up until after the user interacts with the element or clicks off of it.

Same for Add-ons and Customize Mode.

**Comment by schalkneethling** [comment]
@sevaan This is by design. @verdi Thoughts?
