### ISSUE TITLE
NewTab panel should animate in and out

### ISSUE THREAD

**Issue by sevaan** [mozilla/onboard#94]
I think the panel should animate in and out.

Animating in when newtab opens really catches the eye and draws attention to it.

And right now the bar just disappears when a user clicks on the button within it. The panel really should slide back down off the screen. It's a bit jarring otherwise, and it adds a nice bit of polish.

**Comment by schalkneethling** [comment]
We are not doing that for this experiment. And the bar hiding on CTA click is be design. @verdi Agreed?
