### ISSUE TITLE
RC9 - 3 sessions test fails

### ISSUE THREAD

**Issue by Verdi** [mozilla/onboard#99]
Once we display a notification it should be shown on new tabs for 24hrs (30seconds for testing) OR 3 sessions. I tried to test if they would be shown for 3 sessions and then a wait interval would start but what I found was:

After the first notification was shown, I restarted the browser and didn't see that notification anymore. Restarting the browser again got me the 2nd notification but it was only about 18 seconds from receiving the first notification.

Here's a video: https://dl.dropboxusercontent.com/u/105549/3sessions.mp4

We probably need to up that 30 seconds to something more like 60 or 90 seconds in order to properly test this.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mozilla/onboard/pull/101 - Note that the timers are not set to 2 minutes.
